_target_: pytorch_lightning.loggers.WandbLogger
save_dir: .
name: play_lmp
group: play_lmp
log_model: false
project: "baseline_reproduction"
entity: <REPLACE WITH YOUR WANDB ORG> #!! Change me
id: ???
